/**
 * Draws the mark's two derived files from `src/domain/mark.ts`:
 *
 *   src/app/icon.svg    the favicon Next serves, and the only artwork the site
 *                       itself uses at a size bigger than the header chip
 *   src/server/markPng.ts
 *                       the raster the conformance statement embeds, because a
 *                       .docx cannot be trusted to render SVG on a machine
 *                       nobody here controls
 *
 * The raster is a base64 constant rather than a file under `public/`, and that
 * is a deployment decision rather than a stylistic one: `public/` is served
 * from a CDN and is not on the serverless filesystem, so a statement built in
 * production would have found nothing to read. A constant is bundled with the
 * code that uses it, by construction.
 *
 * Run it with `npm run mark`. Both outputs are committed: the statement has to
 * build byte-for-byte the same twice, and a build step that redraws a logo
 * every time is a build step that can quietly redraw it differently.
 *
 * `__tests__/mark.test.ts` re-derives the SVG and fails if the committed file
 * has drifted from the geometry, so forgetting to run this is caught rather
 * than shipped.
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';

import { STROKE, VIEWBOX, TILE_RADIUS, digitsPath, markSvg } from '../src/domain/mark';

/* The navy is `--accent` from globals.css, where the token test measures it. */
const NAVY = '#14457e';
const WHITE = '#ffffff';

/** 128px: four times the header chip, which is enough for a 300dpi print. */
const PNG_SIZE = 128;

const root = process.cwd();

function writeSvg(): void {
  const file = path.join(root, 'src/app/icon.svg');
  writeFileSync(file, `${markSvg(NAVY, WHITE)}\n`);
  console.log(`  src/app/icon.svg   ${VIEWBOX}×${VIEWBOX}`);
}

async function writePng(): Promise<void> {
  // Only this script needs a canvas; nothing under src/domain/ may import one.
  const { createCanvas, Path2D } = await import('@napi-rs/canvas');
  const scale = PNG_SIZE / VIEWBOX;
  const canvas = createCanvas(PNG_SIZE, PNG_SIZE);
  const ctx = canvas.getContext('2d');
  ctx.scale(scale, scale);

  const tile = new Path2D();
  tile.roundRect(0, 0, VIEWBOX, VIEWBOX, TILE_RADIUS);
  ctx.fillStyle = NAVY;
  ctx.fill(tile);

  ctx.strokeStyle = WHITE;
  ctx.lineWidth = STROKE;
  ctx.lineCap = 'round';
  ctx.lineJoin = 'round';
  ctx.stroke(new Path2D(digitsPath()));

  const bytes = canvas.toBuffer('image/png');
  const base64 = bytes.toString('base64').replace(/(.{96})/g, '$1\n  ');
  writeFileSync(
    path.join(root, 'src/server/markPng.ts'),
    [
      '/*',
      ' * The mark, rasterised. Generated by `npm run mark` from',
      ' * `src/domain/mark.ts` — do not edit by hand.',
      ' *',
      ' * It is a constant and not a file under `public/` because `public/` is',
      ' * served from a CDN and is not on the serverless filesystem: a',
      ' * conformance statement built in production could not have read it.',
      ' */',
      '',
      `const BASE64 = \``,
      `  ${base64}\`;`,
      '',
      '/** The bytes the conformance statement embeds at `word/media/mark.png`. */',
      'export function markPng(): Uint8Array {',
      "  return Uint8Array.from(Buffer.from(BASE64.replace(/\\s+/g, ''), 'base64'));",
      '}',
      '',
    ].join('\n'),
  );
  console.log(`  src/server/markPng.ts  ${PNG_SIZE}×${PNG_SIZE}, ${bytes.byteLength} bytes`);
}

console.log('Drawing the mark:');
writeSvg();
await writePng();
